[package]
name = "test-release-automation"
version = "0.1.1"
edition = "2021"
description = "testing release_plz"
homepage = "https://developer.holochain.org"
documentation = "https://developer.holochain.org"
repository = "https://developer.holochain.org"
license = "MIT"

[dependencies]
