[package]
name = "test-release-automation"
version = "0.2.1-dev.1"
edition = "2021"
description = "testing release_plz"
homepage = "https://developer.holochain.org"
documentation = "https://developer.holochain.org"
license = "MIT"
repository = "https://developer.holochain.org"

[dependencies]
