from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = false
disable_changelog = true
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ["main", "main-*"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = ["cargo build --release", "cargo set-version {{version}}"]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
