name: Publish Crates

on:
  push:
    tags:
      - "release-v*" # Only trigger on the global workspace tag

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo bins
        uses: actions/cache@v4
        id: cache-cargo-bins
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-bins-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Log in to crates.io
        run: cargo login ${{ secrets.CARGO_REGISITRY_TOKEN }}

      - name: Publish Crates from Git Tag
        run: cargo workspaces publish --yes --from-git
