name: Release Preparation

on:
  push:
    branches:
      - main
      - main-0.1
      - main-0.2

jobs:
  prepare-release:
    name: Prepare Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for cocogitto to access git history
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cocogitto
        run: cargo install cocogitto

      - name: Get current branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Create timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          git config --global user.name "holochain-release-automation2"
          git config --global user.email "actions@github.com"
          git checkout -b release-${{ steps.timestamp.outputs.timestamp }}

      - name: Bump version
        run: cog bump --auto

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
          commit-message: "chore: prepare release"
          title: "chore: prepare release from ${{ steps.get_branch.outputs.branch }}"
          body: |
            This PR was automatically generated to prepare a new release.

            Changes:
            - Version bump via cocogitto
            - Updated CHANGELOG.md
          branch: release-${{ steps.timestamp.outputs.timestamp }}
          base: ${{ steps.get_branch.outputs.branch }}
          labels: release
